### ISSUE TITLE
 image frame 1597916218194532871 dropped due to queue overflow

### ISSUE THREAD

**Issue by zainmehdi** [berndpfrommer/basalt_ros1#3] opened 2020-08-20 09:32 UTC
Hi,
I had a successful run for basalt ros with recorded bag file but when I try to run it online via direct feed from T265 I am getting the above mentioned error. Is there any remedy to this problem. My gyro data comes at 200 Hz , accel data at 62 Hz and images at 30 Hz.
Thanks

**Comment by berndpfrommer** [comment] 2020-08-20 18:57
hmm. You could bump the queue size, see if that works. But why would it
work when playing from a bag, but not when running real time?
how is the CPU load when you run real time? is the combined load of rs
driver and basalt too much?

**Comment by Sandeldeng** [comment] 2020-08-21 03:27
Errors     << basalt_ros1:cmake /home/chao/workspace/basalt_ros_1/logs/basalt_ros1/build.cmake.001.log
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "basalt" with any
  of the following names:

    basaltConfig.cmake
    basalt-config.cmake

  Add the installation prefix of "basalt" to CMAKE_PREFIX_PATH or set
  "basalt_DIR" to a directory containing one of the above files.  If "basalt"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:26 (find_package)


cd /home/chao/workspace/basalt_ros_1/build/basalt_ros1; catkin build --get-env basalt_ros1 | catkin env -si  /usr/bin/cmake /home/chao/workspace/basalt_ros_1/src/basalt_ros1 --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/chao/workspace/basalt_ros_1/devel/.private/basalt_ros1 -DCMAKE_INSTALL_PREFIX=/home/chao/workspace/basalt_ros_1/install -DCMAKE_BUILD_TYPE=Release; cd -
...............................................................................
Failed     << basalt_ros1:cmake                   [ Exited with code 1 ]       
Failed    <<< basalt_ros1                         [ 0.6 seconds ]  

when I build basalt, there are no such two file generated. What should I do? should change the CMakeList.txt file in basalt?

**Comment by zainmehdi** [comment] 2020-08-21 03:30
@Sandeldeng you have to use instructions mentioned here
https://github.com/berndpfrommer/basalt_ros
I also had the same issue and after following instructions mentioned there it compiled fine,

**Comment by Sandeldeng** [comment] 2020-08-21 04:51
Thanks，I have solved it, and the last commod should use the sudo.

**Comment by Sandeldeng** [comment] 2020-08-21 04:52
@zainmehdi Thanks，I have solved it, and the last commod should use the sudo.

**Comment by Sandeldeng** [comment] 2020-08-21 06:15
@zainmehdi  I can't have anything. 
chao@chao-lp:~/workspace/basalt_ros$ roslaunch basalt_ros1 vio_t265.launch 
... logging to /home/chao/.ros/log/5d527d10-e375-11ea-8a13-9822efdd45f7/roslaunch-chao-lp-18392.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://chao-lp:46335/

SUMMARY
========

CLEAR PARAMETERS
 * /vio_node/

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.6
 * /vio_node/calibration_file: /home/chao/worksp...
 * /vio_node/imu_topics: ['gyro', 'accel']
 * /vio_node/odom_frame_id: basalt_pose_frame
 * /vio_node/world_frame_id: world

NODES
  /
    basalt_to_t265_tf_broadcaster (tf/static_transform_publisher)
    vio_node (basalt_ros1/vio_node)

auto-starting new master
process[master]: started with pid [18402]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 5d527d10-e375-11ea-8a13-9822efdd45f7
process[rosout-1]: started with pid [18413]
started core service [/rosout]
process[vio_node-2]: started with pid [18417]
process[basalt_to_t265_tf_broadcaster-3]: started with pid [18422]
[ INFO] [1597990381.292722442]: loaded calibration file with 2 cameras
marg_H
1e+08     0     0     0     0     0     0     0     0     0     0     0     0     0     0
    0 1e+08     0     0     0     0     0     0     0     0     0     0     0     0     0
    0     0 1e+08     0     0     0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0 1e+08     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0    10     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0    10     0     0     0     0
    0     0     0     0     0     0     0     0     0     0     0    10     0     0     0
    0     0     0     0     0     0     0     0     0     0     0     0   100     0     0
    0     0     0     0     0     0     0     0     0     0     0     0     0   100     0
    0     0     0     0     0     0     0     0     0     0     0     0     0     0   100
[ INFO] [1597990381.298089176]: imu subscribing to topics: gyro, accel
[ INFO] [1597990381.300230939]: backend started!

**Comment by zainmehdi** [comment] 2020-08-21 06:25
Did you run your t265 node ? you have to publish video and IMU streams from t265. If you have installed realsense_ros then use rs_t265.launch

**Comment by Sandeldeng** [comment] 2020-08-21 06:39
@zainmehdi  
Yes, but noting else output

**Comment by zainmehdi** [comment] 2020-08-21 06:41
Can you print out your topics and rqt graph ?

**Comment by Sandeldeng** [comment] 2020-08-21 06:45
chao@chao-lp:~/workspace/basalt_ros$ rostopic list
/camera/accel/imu_info
/camera/fisheye1/camera_info
/camera/fisheye1/image_raw
/camera/fisheye1/image_raw/compressed
/camera/fisheye1/image_raw/compressed/parameter_descriptions
/camera/fisheye1/image_raw/compressed/parameter_updates
/camera/fisheye1/image_raw/compressedDepth
/camera/fisheye1/image_raw/compressedDepth/parameter_descriptions
/camera/fisheye1/image_raw/compressedDepth/parameter_updates
/camera/fisheye1/image_raw/theora
/camera/fisheye1/image_raw/theora/parameter_descriptions
/camera/fisheye1/image_raw/theora/parameter_updates
/camera/fisheye2/camera_info
/camera/fisheye2/image_raw
/camera/fisheye2/image_raw/compressed
/camera/fisheye2/image_raw/compressed/parameter_descriptions
/camera/fisheye2/image_raw/compressed/parameter_updates
/camera/fisheye2/image_raw/compressedDepth
/camera/fisheye2/image_raw/compressedDepth/parameter_descriptions
/camera/fisheye2/image_raw/compressedDepth/parameter_updates
/camera/fisheye2/image_raw/theora
/camera/fisheye2/image_raw/theora/parameter_descriptions
/camera/fisheye2/image_raw/theora/parameter_updates
/camera/gyro/imu_info
/camera/imu
/camera/odom/sample
/camera/realsense2_camera_manager/bond
/camera/tracking_module/parameter_descriptions
/camera/tracking_module/parameter_updates
/clicked_point
/diagnostics
/initialpose
/move_base_simple/goal
/rosout
/rosout_agg
/tf

**Comment by zainmehdi** [comment] 2020-08-21 06:56
![frames](https://user-images.githubusercontent.com/21212125/90861638-04fe6780-e3c7-11ea-9a5b-41840cd073c7.png)

There is no /vio/odom topic from basalt in your topic list . And please provide rqt_graph output. You shoud have sth like above

**Comment by Sandeldeng** [comment] 2020-08-21 07:14
> 
![rosgraph](https://user-images.githubusercontent.com/18391367/90862671-5c4d0980-e3c0-11ea-85bd-a6f2af54bf62.png)
I dont know why.
[ WARN] [1597993915.305147818]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.305277512]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.305340895]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.320357123]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.320446304]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.320506305]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.320553444]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.338077806]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.338162658]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.338203493]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.351933381]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.352025850]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.352068632]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.367757494]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.367909435]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.367976115]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.383464421]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.383547320]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.383578221]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.399467150]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.399570082]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.399615789]: IMU data dropped due to overflow: q_len = 300
[ WARN] [1597993915.415265856]: IMU data dropped due to overflow: q_len = 300
**In realsense_ros** the  config of  rs_t265.launch if follow


<launch>
  <arg name="serial_no"           default=""/>
  <arg name="usb_port_id"         default=""/>
  <arg name="device_type"         default="t265"/>
  <arg name="json_file_path"      default=""/>
  <arg name="camera"              default="camera"/>
  <arg name="tf_prefix"           default="$(arg camera)"/>

  <arg name="fisheye_width"       default="848"/> 
  <arg name="fisheye_height"      default="800"/>
  <arg name="enable_fisheye1"     default="true"/>
  <arg name="enable_fisheye2"     default="true"/>

  <arg name="fisheye_fps"         default="30"/>

  <arg name="gyro_fps"            default="200"/>
  <arg name="accel_fps"           default="62"/>
  <arg name="enable_gyro"         default="true"/>
  <arg name="enable_accel"        default="true"/>
  <arg name="enable_pose"         default="true"/>

  <arg name="enable_sync"           default="true"/>

  <arg name="linear_accel_cov"      default="0.01"/>
  <arg name="initial_reset"         default="true"/>
  <arg name="unite_imu_method"      default=""/>

  <arg name="publish_odom_tf"     default="true"/>
  
  <group ns="$(arg camera)">
    <include file="$(find realsense2_camera)/launch/includes/nodelet.launch.xml">
      <arg name="tf_prefix"                value="$(arg tf_prefix)"/>
      <arg name="serial_no"                value="$(arg serial_no)"/>
      <arg name="usb_port_id"              value="$(arg usb_port_id)"/>
      <arg name="device_type"              value="$(arg device_type)"/>
      <arg name="json_file_path"           value="$(arg json_file_path)"/>

      <arg name="enable_sync"              value="$(arg enable_sync)"/>

      <arg name="fisheye_width"            value="$(arg fisheye_width)"/>
      <arg name="fisheye_height"           value="$(arg fisheye_height)"/>
      <arg name="enable_fisheye1"          value="$(arg enable_fisheye1)"/>
      <arg name="enable_fisheye2"          value="$(arg enable_fisheye2)"/>

      <arg name="fisheye_fps"              value="$(arg fisheye_fps)"/>
      <arg name="gyro_fps"                 value="$(arg gyro_fps)"/>
      <arg name="accel_fps"                value="$(arg accel_fps)"/>
      <arg name="enable_gyro"              value="$(arg enable_gyro)"/>
      <arg name="enable_accel"             value="$(arg enable_accel)"/>
      <arg name="enable_pose"              value="$(arg enable_pose)"/>

      <arg name="linear_accel_cov"         value="$(arg linear_accel_cov)"/>
      <arg name="initial_reset"            value="$(arg initial_reset)"/>
      <arg name="unite_imu_method"         value="$(arg unite_imu_method)"/>

      <arg name="publish_odom_tf"          value="$(arg publish_odom_tf)"/>
    </include>
  </group>
</launch>

**Comment by zainmehdi** [comment] 2020-08-21 07:32
<launch>
  <arg name="serial_no"           default=""/>
  <arg name="usb_port_id"         default=""/>
  <arg name="device_type"         default="t265"/>
  <arg name="json_file_path"      default=""/>
  <arg name="camera"              default="camera"/>
  <arg name="tf_prefix"           default="$(arg camera)"/>

  <arg name="fisheye_width"       default="848"/> 
  <arg name="fisheye_height"      default="800"/>
  <arg name="enable_fisheye1"     default="true"/>
  <arg name="enable_fisheye2"     default="true"/>

  


  <arg name="fisheye_fps"         default="30"/>

  <arg name="gyro_fps"            default="200"/>   
  <arg name="accel_fps"           default="62"/>
  <arg name="enable_gyro"         default="true"/>
  <arg name="enable_accel"        default="true"/>
  <arg name="enable_pose"         default="false"/>

  <arg name="enable_sync"           default="false"/>

  <arg name="linear_accel_cov"      default="0.01"/>
  <arg name="initial_reset"         default="false"/>
  <arg name="unite_imu_method"      default="linear_interpolation"/>

  <arg name="publish_odom_tf"     default="true"/>


  
  
  <group ns="$(arg camera)">
    <include file="$(find realsense2_camera)/launch/includes/nodelet.launch.xml">
      <arg name="tf_prefix"                value="$(arg tf_prefix)"/>
      <arg name="serial_no"                value="$(arg serial_no)"/>
      <arg name="usb_port_id"              value="$(arg usb_port_id)"/>
      <arg name="device_type"              value="$(arg device_type)"/>
      <arg name="json_file_path"           value="$(arg json_file_path)"/>

      <arg name="enable_sync"              value="$(arg enable_sync)"/>

      <arg name="fisheye_width"            value="$(arg fisheye_width)"/>
      <arg name="fisheye_height"           value="$(arg fisheye_height)"/>
      <arg name="enable_fisheye1"          value="$(arg enable_fisheye1)"/>
      <arg name="enable_fisheye2"          value="$(arg enable_fisheye2)"/>

      <arg name="fisheye_fps"              value="$(arg fisheye_fps)"/>
      <arg name="gyro_fps"                 value="$(arg gyro_fps)"/>
      <arg name="accel_fps"                value="$(arg accel_fps)"/>
      <arg name="enable_gyro"              value="$(arg enable_gyro)"/>
      <arg name="enable_accel"             value="$(arg enable_accel)"/>
      <arg name="enable_pose"              value="$(arg enable_pose)"/>

      <arg name="linear_accel_cov"         value="$(arg linear_accel_cov)"/>
      <arg name="initial_reset"            value="$(arg initial_reset)"/>
      <arg name="unite_imu_method"         value="$(arg unite_imu_method)"/>

      <arg name="publish_odom_tf"          value="$(arg publish_odom_tf)"/>
    </include>
  </group>
</launch>


You can try this launch file

**Comment by zainmehdi** [comment] 2020-08-21 07:34
[rs_t265.zip](https://github.com/berndpfrommer/basalt_ros1/files/5107432/rs_t265.zip)
Try this launch file

**Comment by zainmehdi** [comment] 2020-08-21 07:42
Update: Please try this one. I can confirm its working on my pc
[rs_t265.zip](https://github.com/berndpfrommer/basalt_ros1/files/5107478/rs_t265.zip)

**Comment by Sandeldeng** [comment] 2020-08-21 07:50
@zainmehdi 
Thank you, but It does not work. Have you do any chang in basalt_ros launch file? when i "catkin build" in basalt_ros , it  have an error, so I used the sudo. I dont konw whether the problem is incur by sudo.

**Comment by zainmehdi** [comment] 2020-08-21 07:52
According to your log your node is up and subscribing there IMU frame dropped happens when you dont use "unite_imu_method:="linear_iterpolation" arg with your launch file. I didnt change anything in basalt end. Only modified t265 launch file

**Comment by Sandeldeng** [comment] 2020-08-21 12:32
@zainmehdi 

> 
![rosgraph](https://user-images.githubusercontent.com/18391367/90890671-05a9f480-e3ed-11ea-8475-5e1d1585b075.png)
[ INFO] [1598013021.781751615]: received image frame rate: 28.1711
[ INFO] [1598013023.461172457]: received combined IMU frame rate: 191.042
[ INFO] [1598013025.115524938]: received image frame rate: 29.9958
[ INFO] [1598013028.449561377]: received image frame rate: 29.9938
[ INFO] [1598013028.453422370]: received combined IMU frame rate: 200.31
[ INFO] [1598013031.783439878]: received image frame rate: 29.9951
[ INFO] [1598013033.447022068]: received combined IMU frame rate: 200.256
[ INFO] [1598013035.116185589]: received image frame rate: 30.0053
[ INFO] [1598013038.437654986]: received combined IMU frame rate: 200.375
[ INFO] [1598013038.449940406]: received image frame rate: 29.9962
[ INFO] [1598013041.783296906]: received image frame rate: 29.9998
[ INFO] [1598013043.429974153]: received combined IMU frame rate: 200.308
[ INFO] [1598013045.116217069]: received image frame rate: 30.0037
[ INFO] [1598013048.428164992]: received combined IMU frame rate: 200.072
[ INFO] [1598013048.450601668]: received image frame rate: 29.9906
[ INFO] [1598013051.783688467]: received image frame rate: 30.0022
[ INFO] [1598013053.415943395]: received combined IMU frame rate: 200.49
[ INFO] [1598013055.118850476]: received image frame rate: 29.9837
[ INFO] [1598013058.406797587]: received combined IMU frame rate: 200.367
[ INFO] [1598013058.452247703]: received image frame rate: 29.9993
[ INFO] [1598013061.783564992]: received image frame rate: 30.0181
[ INFO] [1598013063.398943716]: received combined IMU frame rate: 200.315
[ INFO] [1598013065.117352660]: received image frame rate: 29.996
[ INFO] [1598013068.391390183]: received combined IMU frame rate: 200.303
Only show received image rate and imu frame rate, but give no pose. Can you give you result in success.

**Comment by zainmehdi** [comment] 2020-08-21 12:40
@Sandeldeng It means its running. You can run rviz to visualize poses. In order to visualize trajectory use hector trajectory server and add it as a node in your vio.launch file. CHange the source and target frames in that to world and odom and you should be able to see the trajectory. Unfortunately, I am not at work right now so I dont have that launch file with me.

**Comment by zainmehdi** [comment] 2020-08-21 12:43
```
 <node pkg="hector_trajectory_server" type="hector_trajectory_server" name="basalt_trajectory" ns="basalt" >
        <param name="/target_frame_name" value="odom" />
        <param name="/source_frame_name" value="world" />
        <param name="/trajectory_update_rate" value="10.0" />
        <param name="/trajectory_publish_rate" value="10.0" />
    </node>
```
 Add this to your vio.launch file after installing hector trajectory server.
Then when you open rviz add path and choose the proper topic "basalt_trajectory" in this case.

**Comment by Sandeldeng** [comment] 2020-08-21 13:25
@zainmehdi 
I add it to the vio.launch, and git clone the hector_trajectory_server to my workspace in the basalt_ros and sudo catkin build. after i run roslaunch basalt_ros1 vio.launch. and in the rviz, I can't get the trajectory, The error is Fixed Frame [map] does not exist.

**Comment by zainmehdi** [comment] 2020-08-21 13:27
choose "world" in the fixed frame. There is no frame map.

**Comment by Sandeldeng** [comment] 2020-08-21 13:45
Thank you ! I have solve it, you are a kind friend.

**Comment by berndpfrommer** [comment] 2020-08-21 14:53
@Sandeldeng if your system is set up you should not need any sudo
@zainmehdi did you find out why you had queue overflow?

**Comment by zainmehdi** [comment] 2020-08-21 15:33
@berndpfrommer Actually I couldnt,  the memory and cpu usage wasnt that much. I think it had to do with using the synced option in t265 launch file. I will investigate a bit more and update as soon as I can.

**Comment by Sandeldeng** [comment] 2020-08-25 06:55
@zainmehdi when I use realsense t265 run the system, the system work well. but when I use the mynteye S1040, often failure after few second. the fov of mynteye S1040 is D:146 degree, H:122 degree, V: 76 degree, I have calibrated it with kd4 and ds model. So I want to ask you if the system not suit for the low fov of 76 degree. Thank you.

**Comment by zainmehdi** [comment] 2020-08-25 07:52
Yes if the fov is lower it will lose tracking often because of not enough features. You can try to reduce your speed of motion to see if it tracks well.

**Comment by Sandeldeng** [comment] 2020-08-25 07:57
@zainmehdi  oh, thank you for your reply. You are a kind man. Thank you again.

**Comment by Sandeldeng** [comment] 2020-08-26 05:42
@zainmehdi when i use the rviz to show the trajectory, I found the pose of the camera is fixed, and the trajectory is move  when I move my realsense t265.

**Comment by Sandeldeng** [comment] 2020-09-02 13:30
@zainmehdi Have you solved the image queue overflow.

**Comment by zainmehdi** [comment] 2020-09-03 07:46
@Sandeldeng It happens sometimes but when I used synced option in the parameters the error goes away. You can try with that.
`<arg name="enable_sync"              value="true"/>`

**Comment by Sandeldeng** [comment] 2020-09-08 01:46
@zainmehdi  yes, but when I use the t265 indoor. I found the left image and right image was not sync when the light not well.

**Comment by zainmehdi** [comment] 2020-09-08 02:11
@Sandeldeng thats strange. They should be synchronized. What platform are you using ?

**Comment by Sandeldeng** [comment] 2020-09-08 02:33
thinkpad e480. and intel NUC. the same config, when I used in the outdoor, the weather is sun, the sync is no problem.

**Comment by zainmehdi** [comment] 2020-09-08 02:39
I think it should be opposite. In my case it works really good indoors but outdoor ambient light affects the performance. You can try after turning the sync option off and see how the performance changes. To be honest I never had any sync issues at my end. I also didnt use basalt alot so maybe I didnt test enough to get this issue.

**Comment by berndpfrommer** [comment] 2021-01-27 13:01
closing this issue since there is no more activity.

**Closed as completed by berndpfrommer** 2021-01-27 13:01 UTC
